# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f41f5450411f6a07df2855931ead63173f473bece83eafa1e87460fa714f55a22f7ae7812d0b536fdee4c5c82629c2d360b6ac7e9d4433ec9ebcdd5a529038e

test:
  secret_key_base: bed9f7856e5b11c925426590a2a818765f0688e244e3658da390e97bfc259e80536fcb14a82e9255fa4aec4ede343da79daa63f792e846e1d66ce874c1bbc09e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
